### ISSUE TITLE
Application panicks on first run when upload is clicked

### ISSUE THREAD

**Issue by rofrol** [KongouDesu/BackupGUI#1]
## Environment

1. OS Windows 10
2. git bash

## Steps to reproduce on first run:
1. `cargo run` or `RUST_BACKTRACE=1  cargo run`.
2. Click `Continue`.
3. Click upload button.

```shell
     Running `target\debug\backup_gui_wgpu.exe`
1024x1024
Detected Drive: DirEntry { kind: Directory, name: "C:/", path: "C:/", action: Mutex { data: Exclude }, children: Mutex { data: [] }, indexed: false, expanded: false }
Swapping state to Upload
Detected Drive: DirEntry { kind: Directory, name: "C:/", path: "C:/", action: Mutex { data: Exclude }, children: Mutex { data: [] }, indexed: false, expanded: false }
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', src\files\mod.rs:388:20
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54\/src\libstd\sys_common\backtrace.rs:78
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54\/src\libstd\sys_common\backtrace.rs:59
   3: core::fmt::write
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54\/src\libcore\fmt\mod.rs:1076
   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54\/src\libstd\io\mod.rs:1537
   5: std::sys_common::backtrace::_print
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54\/src\libstd\sys_common\backtrace.rs:62
   6: std::sys_common::backtrace::print
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54\/src\libstd\sys_common\backtrace.rs:49
   7: std::panicking::default_hook::{{closure}}
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54\/src\libstd\panicking.rs:198
   8: std::panicking::default_hook
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54\/src\libstd\panicking.rs:218
   9: std::panicking::rust_panic_with_hook
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54\/src\libstd\panicking.rs:486
  10: std::panicking::begin_panic_handler
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54\/src\libstd\panicking.rs:388
  11: core::panicking::panic_fmt
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54\/src\libcore\panicking.rs:101
  12: core::option::expect_none_failed
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54\/src\libcore\option.rs:1272
  13: core::result::Result<std::fs::File, std::io::error::Error>::unwrap<std::fs::File,std::io::error::Error>
             at C:\Users\roman.frolow\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\result.rs:1005
  14: backup_gui_wgpu::files::DirEntry::deserialize<str*>
             at .\src\files\mod.rs:388
  15: backup_gui_wgpu::ui::upload::start
             at .\src\ui\upload.rs:132
  16: backup_gui_wgpu::gui::GuiProgram::update
             at .\src\gui.rs:489
  17: backup_gui_wgpu::framework::start::{{closure}}
             at .\src\framework.rs:176
  18: winit::platform_impl::platform::event_loop::{{impl}}::run_return::{{closure}}<(),closure-0>
             at C:\Users\roman.frolow\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop.rs:200
  19: alloc::boxed::{{impl}}::call_mut<(winit::event::Event<()>, mut winit::event_loop::ControlFlow*),FnMut<(winit::event::Event<()>, mut winit::event_loop::ControlFlow*)>>
             at C:\Users\roman.frolow\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\liballoc\boxed.rs:1083
  20: winit::platform_impl::platform::event_loop::runner::{{impl}}::call_event_handler::{{closure}}<()>
             at C:\Users\roman.frolow\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop\runner.rs:239
  21: std::panic::{{impl}}::call_once<(),closure-0>
             at C:\Users\roman.frolow\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panic.rs:318
  22: std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,()> 
             at C:\Users\roman.frolow\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panicking.rs:297
  23: winit::window::{{impl}}::clone
  24: std::panicking::try<(),std::panic::AssertUnwindSafe<closure-0>>
             at C:\Users\roman.frolow\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panicking.rs:274
  25: std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()>     
             at C:\Users\roman.frolow\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panic.rs:394
  26: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>::catch_unwind<(),(),closure-0>
             at C:\Users\roman.frolow\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop\runner.rs:150
  27: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>::call_event_handler<()>
             at C:\Users\roman.frolow\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop\runner.rs:233
  28: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>::send_event<()>
             at C:\Users\roman.frolow\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop\runner.rs:218
  29: winit::platform_impl::platform::event_loop::SubclassInput<()>::send_event<()>
             at C:\Users\roman.frolow\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop.rs:90
  30: winit::platform_impl::platform::event_loop::public_window_callback::{{closure}}<()>
             at C:\Users\roman.frolow\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop.rs:1159
  31: core::ops::function::FnOnce::call_once<closure-0,()>
             at C:\Users\roman.frolow\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\ops\function.rs:232
  32: std::panic::{{impl}}::call_once<isize,closure-0>
             at C:\Users\roman.frolow\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panic.rs:318
  33: std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,isize>
             at C:\Users\roman.frolow\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panicking.rs:297
  34: std::panicking::try::do_catch<std::panic::AssertUnwindSafe<closure-0>,isize>
  35: std::panicking::try<isize,std::panic::AssertUnwindSafe<closure-0>>       
             at C:\Users\roman.frolow\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panicking.rs:274
  36: std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,isize>  
             at C:\Users\roman.frolow\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panic.rs:394
  37: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>::catch_unwind<(),isize,closure-0>
             at C:\Users\roman.frolow\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop\runner.rs:150
  38: winit::platform_impl::platform::event_loop::public_window_callback<()>   
             at C:\Users\roman.frolow\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop.rs:1893
  39: DefSubclassProc
  40: DefSubclassProc
  41: CallWindowProcW
  42: CallWindowProcW
  43: glPushClientAttrib
  44: CallWindowProcW
  45: DispatchMessageW
  46: winit::platform_impl::platform::event_loop::EventLoop<()>::run_return<(),closure-0>
             at C:\Users\roman.frolow\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop.rs:215
  47: winit::platform_impl::platform::event_loop::EventLoop<()>::run<(),closure-0>
             at C:\Users\roman.frolow\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop.rs:185
  48: winit::event_loop::EventLoop<()>::run<(),closure-0>
             at C:\Users\roman.frolow\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\event_loop.rs:149
  49: backup_gui_wgpu::framework::start
             at .\src\framework.rs:132
  50: backup_gui_wgpu::framework::run
             at .\src\framework.rs:193
  51: backup_gui_wgpu::main
             at .\src\main.rs:11
  52: std::rt::lang_start::{{closure}}<()>
             at C:\Users\roman.frolow\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\rt.rs:67
  53: std::rt::lang_start_internal::{{closure}}
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54\/src\libstd\rt.rs:52
  54: std::panicking::try::do_call
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54\/src\libstd\panicking.rs:297
  55: std::panicking::try
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54\/src\libstd\panicking.rs:274
  56: std::panic::catch_unwind
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54\/src\libstd\panic.rs:394
  57: std::rt::lang_start_internal
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54\/src\libstd\rt.rs:51
  58: std::rt::lang_start<()>
             at C:\Users\roman.frolow\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\rt.rs:67
  59: main
  60: invoke_main
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:64      
  61: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253     
  62: BaseThreadInitThunk
  63: RtlUserThreadStart
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\backup_gui_wgpu.exe` (exit code: 101)
```

**Comment by KongouDesu** [comment]
Should be fixed in 3c4b862ce5803a6a416016d4d3a73e9c5c121e7b  
It was crashing because `backuplist.dat` couldn't be found. It is only created once the file-tree is closed.   
It will now display an error message instead of crashing.
